# Generated by Django 5.0.3 on 2024-04-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_orderd_date_orderplaced_ordered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Acceptting', 'Acceptting'), ('Packed', 'Packed'), ('On The Way ', 'On The Way'), ('Delivred', 'Delivred'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
    ]
